import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 1400, height: 950 } })
await page.goto('http://localhost:4176/'); await page.waitForTimeout(400)
await page.getByRole('button', { name: 'Before · legacy' }).click(); await page.waitForTimeout(300)
await page.getByRole('button', { name: '► Advanced Options' }).click(); await page.waitForTimeout(200)
await page.screenshot({ path: 'shots/desktop-legacy.png' })
await page.getByRole('button', { name: /Annotation 3/ }).click(); await page.waitForTimeout(200)
await page.screenshot({ path: 'shots/desktop-legacy-pin.png' })
await browser.close(); console.log('ok')
